In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_brazil = pd.read_excel(r'alldatasets.xlsx',sheet_name='Brazil')

In [3]:
df_brazil.head()

,childid,country,height,stunting_2cat,EDUYRS2,z_score,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn_usd
0,BR1,Brazil,180.35,0.0,16.0,0.399053,0.0,5.0,1,50.0,3.0,0.306352,3.0,1,290.316010
1,BR2,Brazil,164.95,0.0,15.0,0.002132,NaN,5.0,0,52.0,3.0,0.533106,3.0,1,109.973544
2,BR8,Brazil,167.10,1.0,5.0,-2.061853,6.0,5.0,1,49.0,12.0,0.115514,3.0,1,109.973544
3,BR12,Brazil,174.75,0.0,13.0,1.351661,2.0,6.0,1,51.0,5.0,0.597647,3.0,1,1060.838040
4,BR14,Brazil,179.35,0.0,11.0,0.557821,NaN,10.0,1,50.0,3.0,0.483788,3.0,1,353.612680

In [4]:
df_brazil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   childid        2398 non-null   object
 1   country        2398 non-null   object
 2   height         2354 non-null   float64
 3   stunting_2cat  2140 non-null   float64
 4   EDUYRS2        2396 non-null   float64
 5   z_score        2378 non-null   float64
 6   agegapr1       1784 non-null   float64
 7   momeduyrsr1    2393 non-null   float64
 8   chsexr1        2398 non-null   int64
 9   agemonr1       2143 non-null   float64
 10  hhsizer1       2192 non-null   float64
 11  wi_newr1       2187 non-null   float64
 12  job_cat        2396 non-null   float64
 13  pvt_sector     2398 non-null   int64
 14  earn_usd       2398 non-null   float64
dtypes: float64(11), int64(2), object(2)
memory usage: 281.1+ KB

In [5]:
df_brazil.describe()

,height,stunting_2cat,EDUYRS2,z_score,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn_usd
count,2354.000000,2140.000000,2396.000000,2378.000000,1784.000000,2393.000000,2398.000000,2143.000000,2192.000000,2187.000000,2396.000000,2398.0,2398.000000
mean,168.869180,0.103271,10.733932,-0.069707,4.492713,6.181362,0.575897,43.106393,4.686588,0.491544,2.839733,1.0,308.578527
std,9.094512,0.304384,3.818078,0.940789,4.051955,3.847929,0.494309,3.676568,1.858736,0.183537,0.546180,0.0,442.847452
min,138.500000,0.000000,0.000000,-3.570150,0.000000,0.000000,0.000000,35.000000,2.000000,0.000000,1.000000,1.0,0.000000
25%,161.750000,0.000000,8.000000,-0.791708,2.000000,4.000000,0.000000,40.000000,3.000000,0.363159,3.000000,1.0,127.388968
50%,169.100000,0.000000,11.000000,-0.077252,3.000000,5.000000,1.000000,43.000000,4.000000,0.494310,3.000000,1.0,212.079205
75%,175.650000,0.000000,13.500000,0.557821,6.000000,8.000000,1.000000,46.000000,5.000000,0.597647,3.000000,1.0,335.932046
max,196.100000,1.000000,21.000000,2.701190,31.000000,20.000000,1.000000,52.000000,17.000000,1.000000,4.000000,1.0,8840.317000

In [6]:
df_brazil=df_brazil.astype({"chsexr1": 'object', "job_cat": 'object', "pvt_sector": 'object',"stunting_2cat": 'object'})

In [7]:
df_brazil.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1         float64
hhsizer1         float64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn_usd         float64
dtype: object

In [8]:
df_outlier=df_brazil.copy()

In [9]:
df_outlier.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1         float64
hhsizer1         float64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn_usd         float64
dtype: object

In [10]:
total = df_outlier.isnull().sum().sort_values(ascending=False)
percent = (df_outlier.isnull().sum()/df_outlier.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Missing Percent'])
missing_data['Missing Percent'] = missing_data['Missing Percent'].apply(lambda x: x * 100)
missing_data.loc[missing_data['Missing Percent'] > 95]

Empty DataFrame
Columns: [Total, Missing Percent]
Index: []

In [11]:
df_outlier=df_outlier.select_dtypes(include=['int64','floating'])

In [12]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
agegapr1       float64
momeduyrsr1    float64
agemonr1       float64
hhsizer1       float64
wi_newr1       float64
earn_usd       float64
dtype: object

In [13]:
import warnings

warnings.filterwarnings('ignore')

In [14]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
agegapr1       float64
momeduyrsr1    float64
agemonr1       float64
hhsizer1       float64
wi_newr1       float64
earn_usd       float64
dtype: object

In [15]:
#sns.pairplot(df_outlier)

# Outlier Cappping

In [16]:
def cap_data(df):
    for col in df.columns:
        print("capping the ",col)
        if (((df[col].dtype)=='float64') | ((df[col].dtype)=='int64') | ((df[col].dtype)=='float32')):
            percentiles = df[col].quantile([0.01,0.99]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
        else:
            df[col]=df[col]
    return df

In [17]:
final_df=cap_data(df_outlier)

capping the  height
capping the  EDUYRS2
capping the  z_score
capping the  agegapr1
capping the  momeduyrsr1
capping the  agemonr1
capping the  hhsizer1
capping the  wi_newr1
capping the  earn_usd

In [18]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

In [19]:
df_brazil=df_brazil.drop(['childid','country'],axis=1)

In [20]:
all_category_features=df_brazil.select_dtypes(include='object')

In [21]:
all_category_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  2140 non-null   object
 1   chsexr1        2398 non-null   object
 2   job_cat        2396 non-null   object
 3   pvt_sector     2398 non-null   object
dtypes: object(4)
memory usage: 75.1+ KB

# KNN for Categories

In [22]:
mm = MinMaxScaler()

def find_category_mappings(df, variable):
    return {k: i for i, k in enumerate(df[variable].dropna().unique(), 0)}

def integer_encode(df , variable, ordinal_mapping):
    df[variable] = df[variable].map(ordinal_mapping)

mappin = dict()
def imputation(df1 , cols):
    df = df1.copy()
    #Encoding dict &amp; Removing nan    
    #mappin = dict()
    for variable in cols:
        mappings = find_category_mappings(df, variable)
        mappin[variable] = mappings

    #Apply mapping
    for variable in cols:
        integer_encode(df, variable, mappin[variable])  

    #Minmaxscaler and KNN imputation 
    sca = mm.fit_transform(df)
    knn_imputer = KNNImputer()
    knn = knn_imputer.fit_transform(sca)
    df.iloc[:,:] = mm.inverse_transform(knn)
    for i in df.columns : 
        df[i] = round(df[i]).astype('int')

    #Inverse transform
    for i in cols:
        inv_map = {v: k for k, v in mappin[i].items()}
        df[i] = df[i].map(inv_map)
    return df

In [23]:
df_cat_imp=imputation(all_category_features,['stunting_2cat','chsexr1','job_cat','pvt_sector'])

In [24]:
df_cat_imp.isnull().sum().sort_values(ascending = False)

pvt_sector       0
job_cat          0
chsexr1          0
stunting_2cat    0
dtype: int64

In [25]:
df_cat_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  2398 non-null   float64
 1   chsexr1        2398 non-null   int64
 2   job_cat        2398 non-null   float64
 3   pvt_sector     2398 non-null   int64
dtypes: float64(2), int64(2)
memory usage: 75.1 KB

In [26]:
#df_cat_imp.to_csv(r'C:\Users\rramr\OneDrive\Desktop\Modern Scientist Global\Peru\df_knn_before.csv', encoding='utf-8', index=True)

In [27]:
#all_category_features=df_et.select_dtypes(include='o')

In [28]:
#cat_dummies = pd.get_dummies(all_category_features, dummy_na=True)
#cat_dummies.head()

# KNN for numerics

In [29]:
df_knn=final_df.copy()

In [30]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df_num_imp = pd.DataFrame(imputer.fit_transform(df_knn),columns = df_knn.columns)

In [31]:
df_num_imp.head()

,height,EDUYRS2,z_score,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn_usd
0,180.35,16.0,0.399053,0.0,5.0,50.0,3.00,0.306352,290.316010
1,164.95,15.0,0.002132,3.0,5.0,50.0,3.00,0.533106,109.973544
2,167.10,5.0,-2.061853,6.0,5.0,49.0,11.09,0.115514,109.973544
3,174.75,13.0,1.351661,2.0,6.0,50.0,5.00,0.597647,1060.838040
4,179.35,11.0,0.557821,5.2,10.0,50.0,3.00,0.483788,353.612680

In [32]:
df_outlier_concat = pd.concat([df_num_imp, df_cat_imp], axis=1)
df_outlier_concat.head()

,height,EDUYRS2,z_score,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,180.35,16.0,0.399053,0.0,5.0,50.0,3.00,0.306352,290.316010,0.0,1,3.0,1
1,164.95,15.0,0.002132,3.0,5.0,50.0,3.00,0.533106,109.973544,0.0,0,3.0,1
2,167.10,5.0,-2.061853,6.0,5.0,49.0,11.09,0.115514,109.973544,1.0,1,3.0,1
3,174.75,13.0,1.351661,2.0,6.0,50.0,5.00,0.597647,1060.838040,0.0,1,3.0,1
4,179.35,11.0,0.557821,5.2,10.0,50.0,3.00,0.483788,353.612680,0.0,1,3.0,1

In [33]:
df_outlier_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   height         2398 non-null   float64
 1   EDUYRS2        2398 non-null   float64
 2   z_score        2398 non-null   float64
 3   agegapr1       2398 non-null   float64
 4   momeduyrsr1    2398 non-null   float64
 5   agemonr1       2398 non-null   float64
 6   hhsizer1       2398 non-null   float64
 7   wi_newr1       2398 non-null   float64
 8   earn_usd       2398 non-null   float64
 9   stunting_2cat  2398 non-null   float64
 10  chsexr1        2398 non-null   int64
 11  job_cat        2398 non-null   float64
 12  pvt_sector     2398 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 243.7 KB

In [34]:
df_outlier_concat=df_outlier_concat.astype({"stunting_2cat": 'int64'})

In [35]:
df_outlier_concat.head()

,height,EDUYRS2,z_score,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,180.35,16.0,0.399053,0.0,5.0,50.0,3.00,0.306352,290.316010,0,1,3.0,1
1,164.95,15.0,0.002132,3.0,5.0,50.0,3.00,0.533106,109.973544,0,0,3.0,1
2,167.10,5.0,-2.061853,6.0,5.0,49.0,11.09,0.115514,109.973544,1,1,3.0,1
3,174.75,13.0,1.351661,2.0,6.0,50.0,5.00,0.597647,1060.838040,0,1,3.0,1
4,179.35,11.0,0.557821,5.2,10.0,50.0,3.00,0.483788,353.612680,0,1,3.0,1

In [36]:
df_knn_imp=df_outlier_concat.copy()

In [37]:
import statsmodels.api as sm

# cognition

In [38]:
#cognition

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     75.31
Date:                Sun, 09 May 2021   Prob (F-statistic):           7.28e-18
Time:                        18:24:07   Log-Likelihood:                -3185.1
No. Observations:                2398   AIC:                             6374.
Df Residuals:                    2396   BIC:                             6386.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.0221      0.020     -1.126      0.260      -0.060       0.016
stunting_2cat    -0.5598      0.065     -8.678      0.000      -0.686      -0.433
==============================================================================
Omnibus:                       27.502   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.320
Skew:                          -0.007   Prob(JB):                     0.000173
Kurtosis:                       2.584   Cond. No.                         3.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# height

In [39]:
#Height

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.070
Model:                            OLS   Adj. R-squared:                  0.069
Method:                 Least Squares   F-statistic:                     179.1
Date:                Sun, 09 May 2021   Prob (F-statistic):           1.93e-39
Time:                        18:24:07   Log-Likelihood:                -8561.0
No. Observations:                2398   AIC:                         1.713e+04
Df Residuals:                    2396   BIC:                         1.714e+04
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           169.6156      0.184    920.453      0.000     169.254     169.977
stunting_2cat    -8.1230      0.607    -13.382      0.000      -9.313      -6.933
==============================================================================
Omnibus:                      146.666   Durbin-Watson:                   1.985
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.922
Skew:                           0.009   Prob(JB):                     1.95e-12
Kurtosis:                       2.266   Cond. No.                         3.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# education

In [40]:
#education

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.032
Method:                 Least Squares   F-statistic:                     81.42
Date:                Sun, 09 May 2021   Prob (F-statistic):           3.65e-19
Time:                        18:24:08   Log-Likelihood:                -6554.1
No. Observations:                2398   AIC:                         1.311e+04
Df Residuals:                    2396   BIC:                         1.312e+04
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            10.9565      0.080    137.297      0.000      10.800      11.113
stunting_2cat    -2.3719      0.263     -9.023      0.000      -2.887      -1.856
==============================================================================
Omnibus:                       35.990   Durbin-Watson:                   2.065
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.082
Skew:                          -0.243   Prob(JB):                     6.55e-08
Kurtosis:                       2.692   Cond. No.                         3.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# cognition covariates

In [41]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.238
Model:                            OLS   Adj. R-squared:                  0.236
Method:                 Least Squares   F-statistic:                     106.7
Date:                Sun, 09 May 2021   Prob (F-statistic):          2.93e-136
Time:                        18:24:08   Log-Likelihood:                -2896.2
No. Observations:                2398   AIC:                             5808.
Df Residuals:                    2390   BIC:                             5855.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -1.6042      0.216     -7.425      0.000      -2.028      -1.181
stunting_2cat    -0.2224      0.059     -3.774      0.000      -0.338      -0.107
agemonr1          0.0187      0.005      3.940      0.000       0.009       0.028
chsexr1           0.0625      0.034      1.864      0.063      -0.003       0.128
agegapr1         -0.0027      0.005     -0.555      0.579      -0.012       0.007
momeduyrsr1       0.0634      0.005     12.276      0.000       0.053       0.073
hhsizer1         -0.0665      0.010     -6.430      0.000      -0.087      -0.046
wi_newr1          1.3063      0.111     11.757      0.000       1.088       1.524
==============================================================================
Omnibus:                       14.698   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               10.582
Skew:                          -0.016   Prob(JB):                      0.00504
Kurtosis:                       2.676   Cond. No.                         577.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Height covariates

In [42]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.571
Model:                            OLS   Adj. R-squared:                  0.570
Method:                 Least Squares   F-statistic:                     455.3
Date:                Sun, 09 May 2021   Prob (F-statistic):               0.00
Time:                        18:24:08   Log-Likelihood:                -7631.3
No. Observations:                2398   AIC:                         1.528e+04
Df Residuals:                    2390   BIC:                         1.532e+04
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           159.2381      1.557    102.303      0.000     156.186     162.290
stunting_2cat    -7.6668      0.425    -18.057      0.000      -8.499      -6.834
agemonr1          0.0288      0.034      0.844      0.399      -0.038       0.096
chsexr1          12.6942      0.242     52.500      0.000      12.220      13.168
agegapr1         -0.0411      0.035     -1.180      0.238      -0.109       0.027
momeduyrsr1       0.1891      0.037      5.086      0.000       0.116       0.262
hhsizer1          0.0634      0.074      0.852      0.394      -0.083       0.209
wi_newr1          1.0271      0.800      1.283      0.200      -0.543       2.597
==============================================================================
Omnibus:                        2.808   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.246   Jarque-Bera (JB):                2.857
Skew:                           0.073   Prob(JB):                        0.240
Kurtosis:                       2.916   Cond. No.                         577.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# education covariates

In [43]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.316
Model:                            OLS   Adj. R-squared:                  0.314
Method:                 Least Squares   F-statistic:                     157.5
Date:                Sun, 09 May 2021   Prob (F-statistic):          1.18e-191
Time:                        18:24:08   Log-Likelihood:                -6139.4
No. Observations:                2398   AIC:                         1.229e+04
Df Residuals:                    2390   BIC:                         1.234e+04
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             7.2003      0.836      8.618      0.000       5.562       8.839
stunting_2cat    -0.7993      0.228     -3.507      0.000      -1.246      -0.352
agemonr1          0.0188      0.018      1.023      0.306      -0.017       0.055
chsexr1          -0.7865      0.130     -6.060      0.000      -1.041      -0.532
agegapr1         -0.0277      0.019     -1.482      0.138      -0.064       0.009
momeduyrsr1       0.3108      0.020     15.570      0.000       0.272       0.350
hhsizer1         -0.3119      0.040     -7.801      0.000      -0.390      -0.233
wi_newr1          5.9395      0.430     13.823      0.000       5.097       6.782
==============================================================================
Omnibus:                       75.757   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               83.850
Skew:                          -0.421   Prob(JB):                     6.20e-19
Kurtosis:                       3.361   Cond. No.                         577.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""